/*
 * Created on Nov 25, 2003
 *
 * IDocumentMouseListener
 */
package edu.virginia.speclab.ivanhoe.client.game.model.document;

import edu.virginia.speclab.ivanhoe.shared.data.*;

/**
 * @author lfoster
 *
 * Interface to handle mouse events generated by the IvanhoeDocument
 */
public interface IDocumentMouseListener
{
   void tagEntered(String tagDetails);
   void tagExited();
   void linkActivated(Link target);
}
