# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "action", :force => true do |t|
    t.column "fk_type",            :integer,               :default => 0, :null => false
    t.column "tag_id",             :text
    t.column "date",               :datetime
    t.column "offset",             :integer,  :limit => 8
    t.column "data",               :text
    t.column "fk_adopted_from_id", :integer
  end

  create_table "action_type", :force => true do |t|
    t.column "name", :string, :limit => 20
  end

  create_table "action_version", :id => false, :force => true do |t|
    t.column "fk_action_id",           :integer, :default => 0, :null => false
    t.column "fk_document_version_id", :integer, :default => 0, :null => false
  end

  create_table "bookmarks", :force => true do |t|
    t.column "fk_game_id", :integer, :default => 0,  :null => false
    t.column "label",      :string,  :default => ""
    t.column "url",        :string,  :default => ""
    t.column "summary",    :text,    :default => "", :null => false
  end

  create_table "category", :force => true do |t|
    t.column "name",        :string,  :default => ""
    t.column "description", :text,    :default => "", :null => false
    t.column "fk_game_id",  :integer, :default => 0,  :null => false
  end

  create_table "db_history", :id => false, :force => true do |t|
    t.column "entry_date",   :string, :limit => 20
    t.column "entry",        :string, :limit => 50
    t.column "host_version", :string, :limit => 20
  end

  create_table "discourse_field", :id => false, :force => true do |t|
    t.column "fk_game_id",     :integer, :default => 0,     :null => false
    t.column "fk_document_id", :integer, :default => 0,     :null => false
    t.column "starting_doc",   :boolean, :default => true
    t.column "published_doc",  :boolean, :default => false
  end

  create_table "discussion", :force => true do |t|
    t.column "fk_role_id", :integer,                :default => 0,  :null => false
    t.column "fk_game_id", :integer,                :default => 0,  :null => false
    t.column "title",      :string,   :limit => 50, :default => "", :null => false
    t.column "message",    :text,                   :default => "", :null => false
    t.column "post_date",  :datetime,                               :null => false
    t.column "parent_id",  :integer,                :default => 0
  end

  create_table "document", :force => true do |t|
    t.column "file_name",         :string
    t.column "title",             :string,   :limit => 50
    t.column "author",            :string,                  :default => "Unknown"
    t.column "publication_date",  :string,   :limit => 20,  :default => "Unknown"
    t.column "provenance",        :string,   :limit => 100, :default => "Unknown"
    t.column "length",            :integer
    t.column "add_date",          :datetime,                                       :null => false
    t.column "fk_contributor_id", :integer,                 :default => 0
  end

  create_table "document_image", :id => false, :force => true do |t|
    t.column "fk_document_id", :integer, :default => 0, :null => false
    t.column "file_name",      :string
  end

  create_table "document_version", :force => true do |t|
    t.column "fk_document_id", :integer,  :default => 0,     :null => false
    t.column "fk_role_id",     :integer,  :default => 0,     :null => false
    t.column "date",           :datetime,                    :null => false
    t.column "parent_id",      :integer
    t.column "published",      :boolean,  :default => false
  end

  create_table "game", :force => true do |t|
    t.column "fk_creator_id",  :integer,               :default => 0,     :null => false
    t.column "name",           :string,  :limit => 50
    t.column "description",    :text
    t.column "objectives",     :text
    t.column "archived",       :boolean,               :default => false
    t.column "restricted",     :boolean,               :default => false
    t.column "private",        :boolean,               :default => false
    t.column "retired",        :boolean,               :default => false
    t.column "startDocWeight", :integer,               :default => 1
  end

  create_table "keyspace", :force => true do |t|
    t.column "tablename",  :string,  :limit => 40, :default => "", :null => false
    t.column "next_value", :integer,               :default => 0,  :null => false
  end

  create_table "link_target", :id => false, :force => true do |t|
    t.column "fk_action_id",           :integer,               :default => 0, :null => false
    t.column "fk_link_type",           :integer,               :default => 0, :null => false
    t.column "link_id",                :text
    t.column "label",                  :string,  :limit => 20
    t.column "data",                   :text
    t.column "fk_document_version_id", :integer,               :default => 0, :null => false
  end

  create_table "link_type", :force => true do |t|
    t.column "name", :string, :limit => 20
  end

  create_table "move", :force => true do |t|
    t.column "fk_game_id",     :integer,  :default => 0, :null => false
    t.column "fk_role_id",     :integer,  :default => 0, :null => false
    t.column "description",    :text
    t.column "start_date",     :datetime
    t.column "submit_date",    :datetime
    t.column "title",          :text
    t.column "fk_category_id", :integer
  end

  create_table "move_action", :id => false, :force => true do |t|
    t.column "fk_move_id",   :integer, :default => 0, :null => false
    t.column "fk_action_id", :integer, :default => 0, :null => false
  end

  create_table "move_inspiration", :id => false, :force => true do |t|
    t.column "inspired_id",      :integer, :default => 0, :null => false
    t.column "inspirational_id", :integer, :default => 0, :null => false
  end

  create_table "player", :force => true do |t|
    t.column "playername",          :string,  :limit => 20,  :default => "",    :null => false
    t.column "password",            :string,  :limit => 32,  :default => "",    :null => false
    t.column "fname",               :string,  :limit => 20
    t.column "lname",               :string,  :limit => 20
    t.column "email",               :string,  :limit => 100
    t.column "affiliation",         :text
    t.column "new_game_permission", :boolean,                :default => false
    t.column "new_role_permission", :boolean,                :default => false
    t.column "write_permission",    :boolean,                :default => false
    t.column "admin",               :boolean,                :default => false
  end

  create_table "player_game", :id => false, :force => true do |t|
    t.column "fk_player_id", :integer, :default => 0, :null => false
    t.column "fk_game_id",   :integer, :default => 0, :null => false
  end

  create_table "player_game_role", :id => false, :force => true do |t|
    t.column "fk_player_id", :integer, :default => 0, :null => false
    t.column "fk_game_id",   :integer, :default => 0, :null => false
    t.column "fk_role_id",   :integer, :default => 0, :null => false
  end

  create_table "role", :force => true do |t|
    t.column "name",             :string,  :limit => 50
    t.column "description",      :text
    t.column "objectives",       :text
    t.column "stroke_rgb",       :integer,               :default => 0
    t.column "fill_rgb",         :integer,               :default => 0
    t.column "write_permission", :boolean,               :default => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

end
