/*
 * Created on Nov 26, 2003
 *
 * IStatusListener
 */
package edu.virginia.speclab.ivanhoe.client.game.model.util;

/**
 * @author lfoster
 *
 * Interface to listen for messages generated by ivanhoe components
 */
public interface IStatusListener
{
   void warningMsgNotification(String message);
   void errorMsgNotification(String message);
}
